### ISSUE TITLE
Content with only a bulleted list shows large white space instead of content

### ISSUE THREAD

**Issue by jwynveen** [iamacup/react-native-markdown-display#124]
When trying to display content that only contains a bulleted list, it only renders each bullet with a large white space after it and doesn't show the text of the bullet. If you add text before or after the list that is separated by a new line, it renders correctly.

Doesn't work:
```
- One bullet
- Two bullet
- Three bullet
```

Works:
```
Intro text
- One bullet
- Two bullet
- Three bullet
```

Works:
```
- One bullet
- Two bullet
- Three bullet
More text
```

**Comment by jwynveen** [comment]
This may have just been a problem of not setting the width of the body, or not setting flexGrow on the body.

**Comment by nabeelpkl** [comment]
any solution?

**Comment by muhsin-k** [comment]
Setting `minWidth` for body should fix the issue.

**Comment by Looveh** [comment]
I can confirm that I'm seeing this issue still on `v7.0.0-alpha.2`
